"""Application constants."""

# Card Networks
CARD_NETWORK_VISA = "visa"
CARD_NETWORK_MASTERCARD = "mastercard"
CARD_NETWORK_AMEX = "amex"
CARD_NETWORK_DISCOVER = "discover"

CARD_NETWORKS = [
    CARD_NETWORK_VISA,
    CARD_NETWORK_MASTERCARD,
    CARD_NETWORK_AMEX,
    CARD_NETWORK_DISCOVER,
]

# Reward Types
REWARD_TYPE_CASHBACK = "cashback"
REWARD_TYPE_POINTS = "points"
REWARD_TYPE_MILES = "miles"

REWARD_TYPES = [
    REWARD_TYPE_CASHBACK,
    REWARD_TYPE_POINTS,
    REWARD_TYPE_MILES,
]

# Common Categories
CATEGORY_GROCERY = "grocery"
CATEGORY_DINING = "dining"
CATEGORY_GAS = "gas"
CATEGORY_TRAVEL = "travel"
CATEGORY_STREAMING = "streaming"
CATEGORY_TRANSIT = "transit"
CATEGORY_GENERAL = "general"

# HTTP Status Codes
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_400_BAD_REQUEST = 400
HTTP_404_NOT_FOUND = 404
HTTP_500_INTERNAL_SERVER_ERROR = 500

